<a href="https://colab.research.google.com/github/Basit2612/Deep-Learning-with-Pytorch/blob/main/00_Fundamentals_of__Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.3.0+cu121


# Introduction to Tensors

Creating Tensors

In [ ]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7, 8],
                       [9, 1]])
print(matrix)

tensor([[7, 8],
        [9, 1]])


In [ ]:
matrix.ndim

2

In [ ]:
matrix[0][0].item()

7

In [ ]:
scalar

tensor(7)

In [ ]:
tensor = torch.tensor([[[1,2],
                        [3,4]],

                       [[5,6],
                        [7,8]]])
print(tensor)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
tensor.ndim

3

In [ ]:
random_tensor = torch.rand(1, 3, 4)
random_tensor.shape

torch.Size([1, 3, 4])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
random_image_tensor

tensor([[[0.1972, 0.6267, 0.7693],
         [0.2651, 0.8812, 0.5870],
         [0.6040, 0.2246, 0.8485],
         ...,
         [0.9127, 0.2067, 0.5577],
         [0.6640, 0.4067, 0.5761],
         [0.0556, 0.7837, 0.7154]],

        [[0.6502, 0.9581, 0.3953],
         [0.1753, 0.1744, 0.6720],
         [0.2702, 0.0195, 0.2606],
         ...,
         [0.0961, 0.3862, 0.6655],
         [0.2990, 0.8876, 0.0386],
         [0.5651, 0.9866, 0.6338]],

        [[0.0089, 0.2082, 0.6508],
         [0.7091, 0.2113, 0.3550],
         [0.2673, 0.9425, 0.0840],
         ...,
         [0.7535, 0.0299, 0.6494],
         [0.1016, 0.7435, 0.1145],
         [0.7693, 0.8893, 0.8508]],

        ...,

        [[0.0037, 0.7269, 0.3331],
         [0.8460, 0.5504, 0.3770],
         [0.3889, 0.6942, 0.8134],
         ...,
         [0.2363, 0.4555, 0.7001],
         [0.3973, 0.5588, 0.6822],
         [0.7499, 0.3338, 0.9041]],

        [[0.6706, 0.4938, 0.2538],
         [0.8179, 0.7431, 0.1399],
         [0.

In [ ]:
zero = torch.zeros(3)
print(zero)

tensor([0., 0., 0.])


In [ ]:
zero.dtype

torch.float32

In [ ]:
range = torch.arange(0, 10)
print(range)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
one_to_ten =  torch.zeros_like(zero)
one_to_ten

tensor([0., 0., 0.])

In [ ]:
tensor_32 = torch.tensor([3.0, 9., 6.],dtype=None,device = "cuda", requires_grad=False)
tensor_32

tensor([3., 9., 6.], device='cuda:0')

In [ ]:
one_to_ten.device

device(type='cpu')

In [ ]:
tf = torch.matmul(tensor_32, tensor_32)
tf

tensor(126., device='cuda:0')

In [ ]:
tensor_32

tensor([3., 9., 6.], device='cuda:0')

In [ ]:
import time
print(time)

<module 'time' (built-in)>


In [ ]:
len(tensor)

2

In [ ]:
%%time
start_time = time.time()
torch.matmul(tensor_32, tensor_32)
end_time = time.time()
total_time = end_time - start_time
total_time

CPU times: user 122 µs, sys: 26 µs, total: 148 µs
Wall time: 154 µs


0.00012159347534179688

In [ ]:
tensor_32.shape

torch.Size([3])

In [ ]:
tensor_32.size(0)

3

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
mat_2 = torch.matmul(tensor_A, tensor_B.T)
mat_2

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
tensor_A @ tensor_B.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
tensor_A * tensor_B

tensor([[ 7, 16],
        [27, 40],
        [55, 72]])

In [ ]:
torch.argmax(tensor_A)

tensor(5)

In [ ]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x = torch.arange(1.,100.,10)
x, x.shape

(tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.]), torch.Size([10]))

In [ ]:
import torch
import numpy as np

array = np.arange(1,10,1).astype(np.float32)
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype

(dtype('float32'), torch.float32)

In [ ]:
tg = torch.arange(1, 10,1)
tg.dtype, tg

(torch.int64, tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
tg.numpy().astype(np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)